#!/usr/bin/env node
/* Generates the two lists that had to be maintained by hand and in step:
   the <script> tags in index.html and the ASSETS array in sw.js. The cache
   name is derived from a hash of everything cached, so a content change
   invalidates installed copies without anyone remembering to bump a number —
   cache.addAll is all-or-nothing, so one missed entry silently broke offline
   mode for every existing install.

     node tools/build.js          rewrite both files
     node tools/build.js --check  fail if they are out of date (used by CI)

   Load order is derived, not configured: engines depend on each other and on
   the data being present, so the order below is the contract. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const check = process.argv.includes('--check');

/* tracks.js first — it is the registry every content file and engine reads.
   app.js last — it boots the app and expects everything else to be present. */
const ENGINE_FIRST = ['assets/js/store.js', 'assets/js/shell.js', 'assets/js/shell-containers.js'];
const ENGINE_LAST = [
  'assets/js/lab.js', 'assets/js/quiz.js', 'assets/js/sandbox.js',
  'assets/js/playbook.js', 'assets/js/review.js', 'assets/js/app.js'
];
const DATA_FIRST = ['assets/js/data/tracks.js', 'assets/js/data/objectives.js'];

const STATIC = [
  './', './index.html', './manifest.webmanifest', './assets/css/style.css',
  './icons/icon.svg', './icons/icon-192.png', './icons/icon-512.png'
];

function dataFiles() {
  const dir = path.join(ROOT, 'assets/js/data');
  const rest = fs.readdirSync(dir)
    .filter(f => f.endsWith('.js'))
    .map(f => 'assets/js/data/' + f)
    .filter(f => DATA_FIRST.indexOf(f) === -1)
    .sort();
  return DATA_FIRST.concat(rest);
}

function scriptOrder() {
  return ENGINE_FIRST.concat(dataFiles(), ENGINE_LAST);
}

function hashOf(files) {
  const h = crypto.createHash('sha256');
  files.forEach(f => {
    const p = path.join(ROOT, f.replace(/^\.\//, ''));
    if (fs.existsSync(p) && fs.statSync(p).isFile()) h.update(fs.readFileSync(p));
  });
  return h.digest('hex').slice(0, 8);
}

/* ── index.html ──────────────────────────────────────────────────────── */
function renderHtml(html) {
  const tags = scriptOrder().map(f => `<script src="${f}"></script>`).join('\n');
  const block = `<!-- generated by tools/build.js — do not edit by hand -->\n${tags}\n<!-- /generated -->`;
  if (/<!-- generated by tools\/build\.js[\s\S]*?<!-- \/generated -->/.test(html)) {
    return html.replace(/<!-- generated by tools\/build\.js[\s\S]*?<!-- \/generated -->/, block);
  }
  /* first run: replace the hand-written run of script tags */
  return html.replace(/<script src="assets\/js\/[^"]+"><\/script>(\s*<script src="assets\/js\/[^"]+"><\/script>)*/,
                      block);
}

/* ── sw.js ───────────────────────────────────────────────────────────── */
function renderSw(sw, assets, cache) {
  const list = assets.map(a => `  '${a}'`).join(',\n');
  return sw
    .replace(/var CACHE = '[^']*';/, `var CACHE = '${cache}';`)
    .replace(/var ASSETS = \[[\s\S]*?\];/,
      `var ASSETS = [\n${list}\n];`);
}

/* ── run ─────────────────────────────────────────────────────────────── */
const assets = STATIC.concat(scriptOrder().map(f => './' + f));
const cache = 'looped-' + hashOf(assets);

const htmlPath = path.join(ROOT, 'index.html');
const swPath = path.join(ROOT, 'sw.js');
const html = fs.readFileSync(htmlPath, 'utf8');
const sw = fs.readFileSync(swPath, 'utf8');
const nextHtml = renderHtml(html);
const nextSw = renderSw(sw, assets, cache);

const stale = [];
if (nextHtml !== html) stale.push('index.html');
if (nextSw !== sw) stale.push('sw.js');

if (check) {
  if (stale.length) {
    console.error('out of date: ' + stale.join(', ') + '\nrun: node tools/build.js');
    process.exit(1);
  }
  console.log('index.html and sw.js are current (' + cache + ', ' + assets.length + ' assets)');
  process.exit(0);
}

fs.writeFileSync(htmlPath, nextHtml);
fs.writeFileSync(swPath, nextSw);
console.log(stale.length ? 'updated ' + stale.join(' and ') : 'already current');
console.log('cache ' + cache + ' · ' + assets.length + ' assets · ' +
            scriptOrder().length + ' scripts');
