#!/usr/bin/env node
/* Generates the two lists that had to be maintained by hand and in step:
   the <script> tags in index.html and the ASSETS array in sw.js. The cache
   name is derived from a hash of everything cached, so a content change
   invalidates installed copies without anyone remembering to bump a number —
   cache.addAll is all-or-nothing, so one missed entry silently broke offline
   mode for every existing install.

     node tools/build.js          rewrite both files
     node tools/build.js --check  fail if they are out of date (used by CI)

   Load order is derived, not configured: engines depend on each other and on
   the data being present, so the order below is the contract. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const check = process.argv.includes('--check');

/* tracks.js first — it is the registry every content file and engine reads.
   app.js last — it boots the app and expects everything else to be present. */
const ENGINE_FIRST = ['assets/js/store.js', 'assets/js/shell.js'];
const ENGINE_LAST = [
  'assets/js/lab.js', 'assets/js/quiz.js', 'assets/js/sandbox.js',
  'assets/js/playbook.js', 'assets/js/review.js', 'assets/js/app.js'
];
/* Shared by every track, so always eager. */
const DATA_FIRST = ['assets/js/data/tracks.js', 'assets/js/data/objectives.js'];

const STATIC = [
  './', './index.html', './manifest.webmanifest', './assets/css/style.css',
  './icons/icon.svg', './icons/icon-192.png', './icons/icon-512.png'
];

/* The registry is the source of truth for which files belong to which track.
   Read it the same way the browser does, without a DOM. */
function tracks() {
  /* tracks.js references `LX` as a bare global, so it needs a real global
     object rather than a function parameter named window */
  const sandbox = {};
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'assets/js/data/tracks.js'), 'utf8'), sandbox);
  return sandbox.LX.tracks;
}

function defaultTrack(list) {
  return list.filter(t => t.default)[0] || list[0];
}

/* Eager: engines, the shared data, and the default track. Everything else is
   injected by LX.track.load() on first switch. */
function scriptOrder() {
  const list = tracks();
  return ENGINE_FIRST.concat(DATA_FIRST, defaultTrack(list).files || [], ENGINE_LAST);
}

/* Cached: eager plus every other track's files, so a track opened for the first
   time still works with no network. */
function allFiles() {
  const list = tracks();
  const out = scriptOrder().slice();
  list.forEach(t => (t.files || []).forEach(f => { if (out.indexOf(f) === -1) out.push(f); }));
  return out;
}

/* A content file nobody claims would silently never load. */
function unclaimed() {
  const list = tracks();
  const claimed = {};
  list.forEach(t => (t.files || []).forEach(f => { claimed[f] = t.id; }));
  DATA_FIRST.forEach(f => { claimed[f] = 'shared'; });
  return fs.readdirSync(path.join(ROOT, 'assets/js/data'))
    .filter(f => f.endsWith('.js'))
    .map(f => 'assets/js/data/' + f)
    .filter(f => !claimed[f]);
}

/* The track picker shows how much each track holds. Lazily loaded tracks have
   not run yet when the sheet is drawn, so a live count reads 0 for every track
   the user has not opened — precisely the ones they are choosing between.
   Generating the numbers here keeps them honest: they cannot drift, because
   --check fails the build the moment the content changes without them. */
function counts() {
  const list = tracks();
  const sandbox = { console: console };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  vm.runInContext('var LX = window.LX = { commands: [], scenarios: [], drills: [], quiz: [],' +
                  ' labs: [], missions: [], playbooks: [], outputQs: [], dangerQs: [] };', sandbox);
  allFiles()
    .filter(f => f.indexOf('assets/js/data/') === 0)
    .forEach(f => vm.runInContext(fs.readFileSync(path.join(ROOT, f), 'utf8'), sandbox, { filename: f }));
  const LX = sandbox.LX;
  const out = {};
  list.forEach(t => {
    const n = (arr) => (arr || []).filter(x => (x.track || 'linux') === t.id).length;
    out[t.id] = n(LX.commands) + n(LX.playbooks) + n(LX.drills) + n(LX.labs) + n(LX.scenarios);
  });
  return out;
}

/* ── data/tracks.js ──────────────────────────────────────────────────── */
function renderTracks(src, tally) {
  const body = Object.keys(tally).map(k => `  ${k}: ${tally[k]}`).join(',\n');
  const block = `/* generated by tools/build.js — do not edit by hand */\n` +
                `LX.trackCounts = {\n${body}\n};\n/* /generated */`;
  return src.replace(/\/\* generated by tools\/build\.js[\s\S]*?\/\* \/generated \*\//, block);
}

function hashOf(files) {
  const h = crypto.createHash('sha256');
  files.forEach(f => {
    const p = path.join(ROOT, f.replace(/^\.\//, ''));
    if (fs.existsSync(p) && fs.statSync(p).isFile()) h.update(fs.readFileSync(p));
  });
  return h.digest('hex').slice(0, 8);
}

/* ── index.html ──────────────────────────────────────────────────────── */
function renderHtml(html) {
  const tags = scriptOrder().map(f => `<script src="${f}"></script>`).join('\n');
  const block = `<!-- generated by tools/build.js — do not edit by hand -->\n${tags}\n<!-- /generated -->`;
  if (/<!-- generated by tools\/build\.js[\s\S]*?<!-- \/generated -->/.test(html)) {
    return html.replace(/<!-- generated by tools\/build\.js[\s\S]*?<!-- \/generated -->/, block);
  }
  /* first run: replace the hand-written run of script tags */
  return html.replace(/<script src="assets\/js\/[^"]+"><\/script>(\s*<script src="assets\/js\/[^"]+"><\/script>)*/,
                      block);
}

/* ── sw.js ───────────────────────────────────────────────────────────── */
function renderSw(sw, assets, cache) {
  const list = assets.map(a => `  '${a}'`).join(',\n');
  return sw
    .replace(/var CACHE = '[^']*';/, `var CACHE = '${cache}';`)
    .replace(/var ASSETS = \[[\s\S]*?\];/,
      `var ASSETS = [\n${list}\n];`);
}

/* ── run ─────────────────────────────────────────────────────────────── */
const orphans = unclaimed();
if (orphans.length) {
  console.error('not claimed by any track in data/tracks.js — these would never load:\n  ' +
    orphans.join('\n  '));
  process.exit(1);
}

/* tracks.js is hashed into the cache name, so its counts have to be settled
   before anything else is generated. */
const tracksPath = path.join(ROOT, 'assets/js/data/tracks.js');
const tracksSrc = fs.readFileSync(tracksPath, 'utf8');
const nextTracks = renderTracks(tracksSrc, counts());
if (!check && nextTracks !== tracksSrc) fs.writeFileSync(tracksPath, nextTracks);

const assets = STATIC.concat(allFiles().map(f => './' + f));
const cache = 'looped-' + hashOf(assets);

const htmlPath = path.join(ROOT, 'index.html');
const swPath = path.join(ROOT, 'sw.js');
const html = fs.readFileSync(htmlPath, 'utf8');
const sw = fs.readFileSync(swPath, 'utf8');
const nextHtml = renderHtml(html);
const nextSw = renderSw(sw, assets, cache);

const stale = [];
if (nextTracks !== tracksSrc) stale.push('assets/js/data/tracks.js');
if (nextHtml !== html) stale.push('index.html');
if (nextSw !== sw) stale.push('sw.js');

if (check) {
  if (stale.length) {
    console.error('out of date: ' + stale.join(', ') + '\nrun: node tools/build.js');
    process.exit(1);
  }
  console.log('index.html and sw.js are current (' + cache + ', ' + assets.length + ' assets)');
  process.exit(0);
}

fs.writeFileSync(htmlPath, nextHtml);
fs.writeFileSync(swPath, nextSw);
console.log(stale.length ? 'updated ' + stale.join(' and ') : 'already current');
console.log('cache ' + cache + ' · ' + assets.length + ' assets cached · ' +
            scriptOrder().length + ' loaded eagerly · ' +
            (allFiles().length - scriptOrder().length) + ' lazy');
